### ISSUE TITLE
Generating records for weapon using template

### ISSUE THREAD

**Issue by zhongjiedong** [Synthesis-Collective/speedandreachfixes#10]
Patcher is generating overrides to enchanted versions of weapons using templates resulting in thousands of unnecessary records.

Suggest ignore weapon records with template field filled

**Comment by radj307** [comment]
I've pushed an experimental fix for this issue to the `dev` branch, can you confirm that it fixes your problem?

Make sure you check this in the speedandreachfixes settings:  
![image](https://user-images.githubusercontent.com/1927798/182208958-6832ae71-3258-48ad-a701-7ee4a3c6c4fd.png)

> ### Switching to the Dev Branch
> Open synthesis and select speedandreachfixes.
> Next to '**Patcher**' select *Branch* if it isn't already selected, uncheck *Main*, then type `dev` into the textbox.
> ![image](https://user-images.githubusercontent.com/1927798/182208575-1d947b3f-86bb-4f17-806d-7032f9a6742d.png)
> 
> If it says there is a blocking error, look for an upgrade icon in the top-right corner to update the profile-level libraries; it should be located here:  
> ![image](https://user-images.githubusercontent.com/1927798/182209273-a42c2c43-bc5b-43f9-b2ce-52a195f46fe7.png)

**Comment by zhongjiedong** [comment]
[speedandreachfixes.txt](https://github.com/Synthesis-Collective/speedandreachfixes/files/9236742/speedandreachfixes.txt)

errored out

**Comment by Noggog** [comment]
Can you upload your settings file?
`[Synth exe location]/Data/[Profile]/Speed and Reach Fixes/`

**Comment by radj307** [comment]
Appears to be an error caused by casting a string to an enum while loading the settings; it mentions a new enum I added since the base Mutagen types tend to show errors in the Synthesis auto-generated settings menu.

**Comment by zhongjiedong** [comment]
[settings.txt](https://github.com/Synthesis-Collective/speedandreachfixes/files/9236799/settings.txt)

**Comment by radj307** [comment]
Ah, the problem seems to be that `DetectionSoundLevel` *(of enum type `ESoundLevel`)* is being serialized as a string instead of a number

**Comment by radj307** [comment]
Ok, I pushed a potential workaround fix https://github.com/Synthesis-Collective/speedandreachfixes/commit/672436d755ce0d0629ed55f0559ce63395436ad5

**Comment by radj307** [comment]
Everything is working on my end; if you're still running into crashing issues try using this settings file instead:  

[settings.txt](https://github.com/Synthesis-Collective/speedandreachfixes/files/9238166/settings.txt)

*(I just applied a regular expression to your settings file that you already uploaded; so you won't lose any settings if you changed them)*

**Comment by zhongjiedong** [comment]
```
1 field modified in record 'SUM_StalhrimWarhammerShockHazard05'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerShockDmgWild05'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerShockHazard06'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerShockDmgWild06'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerShiftingEarth04'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerKillstreak04'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerThresholdDeath04'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerSkyhook04'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerShiftingEarth05'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerKillstreak05'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerThresholdDeath05'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerSkyhook05'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerShiftingEarth06'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerKillstreak06'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerThresholdDeath06'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerSkyhook06'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerDrainArmor04'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerBattleHunger04'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerMomentum04'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerHaltRegen04'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerDrainArmor05'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerBattleHunger05'	( Reach: 0.8 )
1 field modified in record 'SUM_StalhrimWarhammerMomentum05'	( Reach:
```

Looks like it's still touching templated weapons

I'm still on the dev branch though

**Comment by radj307** [comment]
Fixed in https://github.com/Synthesis-Collective/speedandreachfixes/commit/713feafc45248f0f0513c621435b30e518632007

I'll be migrating this to the main branch soon once I give it a once-over

**Comment by radj307** [comment]
Fixed in https://github.com/Synthesis-Collective/speedandreachfixes/commit/5fb406c983d3b70b2723047d1c856e83a43315ae

I'll be migrating this to the main branch once I give it a once-over.

**Comment by zhongjiedong** [comment]
Sorry but it still appears to be touching templated weapons:

```
Successfully modified weapon: EnchSteelSwordFrost02
Successfully modified weapon: EnchSteelSwordFire03
Successfully modified weapon: EnchSteelSwordFire02
Successfully modified weapon: EnchSteelSwordFire01
Successfully modified weapon: EnchIronWarAxeShock03
Successfully modified weapon: EnchIronWarAxeShock02
Successfully modified weapon: EnchIronWarAxeShock01
Successfully modified weapon: EnchIronWarAxeFrost03
Successfully modified weapon: EnchIronWarAxeFrost02
Successfully modified weapon: EnchIronWarAxeFire03
Successfully modified weapon: EnchIronWarAxeFire02
Successfully modified weapon: EnchIronWarAxeFire01
Successfully modified weapon: EnchIronMaceFrost03
Successfully modified weapon: EnchIronMaceFrost02
Successfully modified weapon: EnchIronMaceFrost01
Successfully modified weapon: EnchIronMaceFire03
Successfully modified weapon: EnchIronMaceFire02
Successfully modified weapon: EnchIronMaceFire01
Successfully modified weapon: EnchIronSwordShock03
Successfully modified weapon: EnchIronSwordShock02
Successfully modified weapon: EnchIronSwordShock01
Successfully modified weapon: EnchIronSwordFrost03
Successfully modified weapon: EnchIronSwordFrost02
Successfully modified weapon: EnchIronSwordFire03
Successfully modified weapon: EnchIronSwordFire02
Successfully modified weapon: EnchIronSwordFire01

Finished patching 50302 records.
```

**Comment by radj307** [comment]
The changes have been pushed to the `master` branch, make sure you're using that one; you can re-check the 'Main' box under versioning.

Sorry for any confusion!

**Comment by zhongjiedong** [comment]
Oh I'm an idiot it's got a tickbox now. I thought it was just by default LOL

**Comment by radj307** [comment]
dwbi lol, happens.

My reasoning for leaving the option to disable it open is in case some mod in the future wants to make use of the stats on templated weapons for some purpose. That being said, it is set to `true` by default on the master branch now to benefit the majority of users.

Thank you for the report though, the patcher completes much faster without the redundant work & it exponentially decreases the `esp`'s footprint once completed!
👍
